/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarketbilling;

import dbconnection.Connect;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author amprojects
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Invoice");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Customer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Stock");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenu1.setText("About");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Invoice().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        customer_report();
        product_report();
        supplier_report();
        stock_report();
        jOptionPane1.showMessageDialog(null,"Report generate Successfully"); 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Product().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Customer().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Stock().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Supplier().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables

    private void customer_report() {
    try
      {
          
          DateFormat dt=new SimpleDateFormat("dd/MM/yyyy");
          java.util.Date d1=new java.util.Date();
          String d=dt.format(d1);
  
                Connect c=new Connect();
                Connection con=c.getConnection();
                PreparedStatement pst=con.prepareStatement("select * from shop_customer");
                ResultSet rs=pst.executeQuery();
             
                BufferedWriter bw=new BufferedWriter(new FileWriter("Customer_report.html"));
                ResultSetMetaData rsm=rs.getMetaData();
                System.out.println("ok");
                  
                int cols=rsm.getColumnCount();
                bw.write("<center><h2><font color=green>SUPERMARKET GST BILLING SYSTEM</font></h2>");
                bw.write("<center><h3><u><b><font color=green>Customer Report</font></b></u></h3></center>");
                bw.write("<h4 align=left>"+"DATE :- "+d+"</h4>");
                bw.write("<hr><center>");
                bw.write("<table border=1>");
                bw.write("<tr>");
               System.out.println("ok");   
           for(int i=1;i<=cols;i++)
            bw.write("<th><font color=purple>"+rsm.getColumnLabel(i)+"</font>");
            while(rs.next())
           {
             bw.write("<tr>");
             for(int i=1;i<=cols;i++)
             bw.write("<td>"+rs.getString(i));
           }
             bw.write("</table>");
             bw.write("</center>");
             bw.close();
             con.close();
           
             
                
      }
      catch(Exception ex)
      {
           jOptionPane1.showMessageDialog(null,ex); 
      }    
    }

    private void product_report() {
    try
      {
          
          DateFormat dt=new SimpleDateFormat("dd/MM/yyyy");
          java.util.Date d1=new java.util.Date();
          String d=dt.format(d1);
  
                Connect c=new Connect();
                Connection con=c.getConnection();
                PreparedStatement pst=con.prepareStatement("select * from product");
                ResultSet rs=pst.executeQuery();
             
                BufferedWriter bw=new BufferedWriter(new FileWriter("Product_report.html"));
                ResultSetMetaData rsm=rs.getMetaData();
                System.out.println("ok");
                  
                int cols=rsm.getColumnCount();
                bw.write("<center><h2><font color=green>SUPERMARKET GST BILLING SYSTEM</font></h2>");
                bw.write("<center><h3><u><b><font color=green>Products Report</font></b></u></h3></center>");
                bw.write("<h4 align=left>"+"DATE :- "+d+"</h4>");
                bw.write("<hr><center>");
                bw.write("<table border=1>");
                bw.write("<tr>");
               System.out.println("ok");   
           for(int i=1;i<=cols;i++)
            bw.write("<th><font color=purple>"+rsm.getColumnLabel(i)+"</font>");
            while(rs.next())
           {
             bw.write("<tr>");
             for(int i=1;i<=cols;i++)
             bw.write("<td>"+rs.getString(i));
           }
             bw.write("</table>");
             bw.write("</center>");
             bw.close();
             con.close();
           
             
                
      }
      catch(Exception ex)
      {
           jOptionPane1.showMessageDialog(null,ex); 
      }       
    }

    private void supplier_report() {
    try
      {
          
          DateFormat dt=new SimpleDateFormat("dd/MM/yyyy");
          java.util.Date d1=new java.util.Date();
          String d=dt.format(d1);
  
                Connect c=new Connect();
                Connection con=c.getConnection();
                PreparedStatement pst=con.prepareStatement("select * from supplier");
                ResultSet rs=pst.executeQuery();
             
                BufferedWriter bw=new BufferedWriter(new FileWriter("Supplier_report.html"));
                ResultSetMetaData rsm=rs.getMetaData();
                System.out.println("ok");
                  
                int cols=rsm.getColumnCount();
                bw.write("<center><h2><font color=green>SUPERMARKET GST BILLING SYSTEM</font></h2>");
                bw.write("<center><h3><u><b><font color=green>Supplier Report</font></b></u></h3></center>");
                bw.write("<h4 align=left>"+"DATE :- "+d+"</h4>");
                bw.write("<hr><center>");
                bw.write("<table border=1>");
                bw.write("<tr>");
               System.out.println("ok");   
           for(int i=1;i<=cols;i++)
            bw.write("<th><font color=purple>"+rsm.getColumnLabel(i)+"</font>");
            while(rs.next())
           {
             bw.write("<tr>");
             for(int i=1;i<=cols;i++)
             bw.write("<td>"+rs.getString(i));
           }
             bw.write("</table>");
             bw.write("</center>");
             bw.close();
             con.close();
           
             
                
      }
      catch(Exception ex)
      {
           jOptionPane1.showMessageDialog(null,ex); 
      }       
    }

    private void stock_report() {
    try
      {
          
          DateFormat dt=new SimpleDateFormat("dd/MM/yyyy");
          java.util.Date d1=new java.util.Date();
          String d=dt.format(d1);
  
                Connect c=new Connect();
                Connection con=c.getConnection();
                PreparedStatement pst=con.prepareStatement("select * from stock");
                ResultSet rs=pst.executeQuery();
             
                BufferedWriter bw=new BufferedWriter(new FileWriter("Stock_report.html"));
                ResultSetMetaData rsm=rs.getMetaData();
                System.out.println("ok");
                  
                int cols=rsm.getColumnCount();
                bw.write("<center><h2><font color=green>SUPERMARKET GST BILLING SYSTEM</font></h2>");
                bw.write("<center><h3><u><b><font color=green>CStock Report</font></b></u></h3></center>");
                bw.write("<h4 align=left>"+"DATE :- "+d+"</h4>");
                bw.write("<hr><center>");
                bw.write("<table border=1>");
                bw.write("<tr>");
               System.out.println("ok");   
           for(int i=1;i<=cols;i++)
            bw.write("<th><font color=purple>"+rsm.getColumnLabel(i)+"</font>");
            while(rs.next())
           {
             bw.write("<tr>");
             for(int i=1;i<=cols;i++)
             bw.write("<td>"+rs.getString(i));
           }
             bw.write("</table>");
             bw.write("</center>");
             bw.close();
             con.close();
           
             
                
      }
      catch(Exception ex)
      {
           jOptionPane1.showMessageDialog(null,ex); 
      }        
    }
}
